04_TagHelpers/Models/Employe.cs
namespace _04_TagHelpers.Models
{
    public class Employe
    {

        public int Id { get; set; }

        public string Name { get; set; } = String.Empty;

        public double Salary { get; set; }

        public bool IsActif { get; set; }

        public string Email { get; set; } = String.Empty;

        public EmployeType Type { get; set; } = EmployeType.DEBUTANT;

        public int DepartmentId { get; set; }
    }

    public enum EmployeType
    {
        DEBUTANT = 1, 
        JUNIOR = 2,
        SENIOR = 3
    }
}

04_TagHelpers/Models/ErrorViewModel.cs
namespace _04_TagHelpers.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

04_TagHelpers/Controllers/EmployeController.cs
using _04_TagHelpers.Models;
using Microsoft.AspNetCore.Mvc;

namespace _04_TagHelpers.Controllers
{
    public class EmployeController : Controller
    {

        private readonly ILogger<EmployeController> _logger;

        public EmployeController(ILogger<EmployeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Create(Employe employe)
        {
            // return View(employe);
            return View("CreateHtmlHelpers", employe);
        }

        public IActionResult Bonjour(Employe employe)
        {
            return View(employe);
        }
    }
}

04_TagHelpers/Views/Employe/Bonjour.cshtml
@using _04_TagHelpers.Helpers

@model Employe
@{
    ViewData["Title"] = "Bonour Employe";
}

<h2>Custom Helper</h2>

<employe name="@Model.Name" salary="@Model.Salary" type="@Model.Type" email="@Model.Email" />

@Html.Employe(@Model.Name, @Model.Salary.ToString(), @Model.Type.ToString(), @Model.Email)

04_TagHelpers/Views/Employe/Create.cshtml
@model Employe
@{
    ViewData["Title"] = "Create Employe";
}

<h1>Employe</h1>

<form method="post" asp-action="Bonjour" class="p-3 mt-4">

    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control"/>
    </div>


    <div class="mb-3">
        <label asp-for="Salary"></label>
        <input asp-for="Salary" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Type"></label>
        <select asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<EmployeType>()">
            <option>Please select One</option>
        </select>
    </div>

    <div class="mb-3">
        <label asp-for="IsActif"></label>
        <input asp-for="IsActif" class="form-check-input" />
    </div>

    <div class="mb-3">
        <label asp-for="DepartmentId"></label>
        <input asp-for="DepartmentId" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Create</button>
</form>

04_TagHelpers/Views/Employe/CreateHtmlHelpers.cshtml
@model Employe
@{
    ViewData["Title"] = "Create HTML Employe";
}

<h1>Employe</h1>

@using(Html.BeginForm("Bonjour", "Employe", FormMethod.Post, new { enctype="multipart/form-data"}))
{
    <div class="border p-3 mt-4">
        <div class="mb-3">
            @Html.LabelFor(model => model.Name)
            @Html.TextBoxFor(model => model.Name, new { @class = "form-control"})
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Salary)
            @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" }})
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Email)
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Type)
            @Html.DropDownListFor(model => model.Type, Html.GetEnumSelectList<EmployeType>(), "Select Type", new { @class = "form-control" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.IsActif)
            @Html.EditorFor(model => model.IsActif, new { htmlAttributes = new { @class = "form-check-input" } })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.DepartmentId)
            @Html.EditorFor(model => model.DepartmentId, new { htmlAttributes = new { @class = "form-control" } })

            <button type="submit" class="btn btn-primary" style="width:150px;">Create</button>
        </div>
    </div>
}

04_TagHelpers/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _04_TagHelpers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_04_TagHelpers.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_04_TagHelpers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _04_TagHelpers - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>